### ISSUE TITLE
Usage Script Request

### ISSUE THREAD

**Issue by dstrib** [cxhernandez/cellcount#12]
Would you mind uploading an example script or use-case? I am interested in trying to apply this to some of my research.

**Comment by cxhernandez** [comment]
It's been a while... but, after installing, you can run the basic commands like this:

```bash
$ cell_count download --dataset bbbc005
$ cel_count train_fpn --dataset path/to/bbbc005
$ cel_count train --dataset path/to/bbbc005
```

You can use the help flag for more info about each command

**Comment by dstrib** [comment]
Thanks!
